name: MinimalWFLToCheckDraft

on:
  push:
  pull_request:
    types: [opened, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:          
    check-draft:
        name: Decide if the workflow runs
        runs-on: ubuntu-latest
        outputs:
          is_draft: ${{ steps.check-draft.outputs.is_draft }}
        steps:
            - id: check-draft
              run: |
                echo "is_draft=${{ github.event.pull_request.draft == true }}" >> $GITHUB_OUTPUT

    test:
        name: Test
        runs-on: ubuntu-latest
        needs: check-draft
        if: ${{ needs.check-draft.outputs.is_draft == false }}

        steps:
        - run: echo ${{needs.check-draft.outputs.is_draft}}

    another-test:
        name: Another Test
        runs-on: ubuntu-latest
        needs: check-draft

        steps:
        - run: ${{needs.check-draft.outputs.is_draft}}