name: Approve fork PR workflows on label

on:
  pull_request_target:
    types: [labeled]

permissions:
  actions: write
  pull-requests: read
  contents: read

jobs:
  approve:
    if: github.event.label.name == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Check actor is org member
        id: orgcheck
        run: |
            resp=$(curl -sSL \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/orgs/duckdb/members/${{ github.actor }})
            if echo "$resp" | grep -q '"login"'; then
                echo "${{ github.actor }} is a duckdb org member"
            else
                echo "${{ github.actor }} is NOT in duckdb org"
                exit 1
            fi
  code-quality:
    needs: approve 
    uses: ./.github/workflows/CodeQuality.yml
    secrets: inherit