name: PRCI
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'
      - 'feature'
      - 'v*.*-*'
    paths-ignore:
      - '**.md'
      - 'test/configs/**'
      - '.github/patches/duckdb-wasm/**'
      - '.github/workflows/**'
      - '!.github/workflows/lcov_exclude'
      - '!.github/workflows/Swift.yml'
      - '!.github/workflows/Main.yml'
      - '!.github/workflows/Linuxrelease.yml'
      - '.github/config/out_of_tree_extensions.cmake'
  merge_group:
  pull_request:
    types: [opened, reopened, ready_for_review, converted_to_draft]
    paths-ignore:
      - '**.md'
      - 'test/configs/**'
      - '.github/patches/duckdb-wasm/**'
      - '.github/workflows/**'
      - '!.github/workflows/lcov_exclude'
      - '!.github/workflows/CodeQuality.yml'
      - '.github/config/out_of_tree_extensions.cmake'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  check-draft:
    # We run all other jobs on PRs only if they are not draft PR
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    runs-on: ubuntu-24.04
    steps:
      - name: Preliminary checks on CI 
        run: echo "Event name is ${{ github.event_name }}"

  linux:
    uses: ./.github/workflows/LinuxRelease.yml
  swift:
    uses: ./.github/workflows/Swift.yml
  main:
    uses: ./.github/workflows/Main.yml
      
